name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-containers:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - glibc
          - musl
          - fedora

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Build target image
        run: just build ${{ matrix.target }}

      - name: Export artifacts
        run: just export ${{ matrix.target }}

      - name: Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/${{ matrix.target }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Release Windows (Native)
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install Nushell
        uses: hustcer/setup-nu@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Build Release
        run: just build windows-native

      - name: Prepare Artifact
        run: just export windows-native



      - name: Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/windows/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
